### ISSUE TITLE
ENH: fetch_logs should work for containers 

### ISSUE THREAD

**Issue by patr1ckm** [civisanalytics/civis-r#105]
This probably never really worked, but I'll report anyway:

```
job <- scripts_post_r(name = "test", source = "2+2")
run <- scripts_post_r_runs(job$id)
x <- scripts_get_r_runs(job$id, run$id)
fetch_logs(x)
```

Produces
```
 Error in do.call(f, c(args, limit = limit)) : 
  second argument must be a list 
```

**Comment by keithing** [comment]
Fortunately, this does work if we use

```r
x <- await(scripts_get_r_runs, id = job$id, run_id = run$id)
fetch_logs(x)
```

`await` adds some metadata to the call that can be used for log fetching.  This makes sense to me, since one would only get logs for a job which takes time to run (and hence requires await).  I think best here would be to add some logic to force `await` to try to print logs when it errors.

**Comment by patr1ckm** [comment]
Ohhhhh, I remember now. Thanks. I'll close this issue.

Getting the original example to work would require attaching the function name as an attribute of the parsed API response.
