### ISSUE TITLE
BUG: can now use 'hyperband' with stacking

### ISSUE THREAD

**Issue by patr1ckm** [civisanalytics/civis-r#131]
We can now use hyperband with stacking, we should not throw an error in `create_and_run_model`.

@elsander can we hyperband with `sparse_logistic` or `sparse_linear_regressor`?

**Comment by elsander** [comment]
It's not possible to use hyperband with GLMs because of how the algorithm is structured. Essentially, you need some parameter to iterate over (# epochs, # trees) during hyperband, and there isn't a parameter like that for GLMs. Fortunately, they're pretty fast to train anyway, so grid search should get the job done fine :)

**Comment by patr1ckm** [comment]
Great, thanks!
