### ISSUE TITLE
ENH: docs website discoverability

### ISSUE THREAD

**Issue by patr1ckm** [civisanalytics/civis-r#184]
It looks like the doc website isn't indexed by google. IT pointed me to this: 

https://help.github.com/en/articles/search-engine-optimization-for-github-pages

Which might enable better docs discoverability.

**Comment by elsander** [comment]
It looks like the page linked above redirects to a more general page now (not about SEO), but I did find this, which might be relevant: https://github.com/jekyll/jekyll-seo-tag

**Comment by elsander** [comment]
I can confirm that at the time of this comment, searching "civis-r api client" and "civis api client r" do not show the doc website in the first page of google results.

Some options we could consider:
* index the page under the `civisanalytics` domain, which might be more trusted by google
* raise the visibility of the documentation website by linking to it in the DESCRIPTION (so that it appears on CRAN, which will likely always appear before our own website)
* sign up for [google search console](https://search.google.com/search-console/about) to determine what phrases our website comes up for (which is maybe not many, based on my preliminary searching)
* change the main page title from "Civis Data Science API Client" to "Civis R API Client", which may help it show up in R-specific searches. This also matches the format of the Python client title.

I pulled many of these suggestions from this thread: https://community.rstudio.com/t/pkgdown-site-seo/26706/2

Any thoughts @patr1ckm ? Updating DESCRIPTION and title are the easiest changes, and seem worth trying to me.

**Comment by patr1ckm** [comment]
Thanks so much for looking at this! 

The query 'Civis Data Science API Client' immediately returned our docs. Changing the title to `Civis R API Client` should probably help.

<img width="529" alt="Screen Shot 2020-02-17 at 9 58 06 AM" src="https://user-images.githubusercontent.com/427445/74669092-16428f00-516c-11ea-94b5-539d0e3c2e2e.png">

I also think that a direct link in the package DESCRIPTION would make it more discoverable with low lift.

I think the other two options sound more involved.
